#!/usr/bin/env bash

# this checks to see if an arg after the executable is greater than 0
# then its just a basic if else statement
#!/usr/bin/env bash

if [ $# -gt 0 ]; then

    # checking for the first command which is the $1 variable
    if [ "$1" == "start" ]; then
        docker-compose up -d

    elif [ "$1" == "stop" ]; then
        docker-compose down

    # looks for artisan or art
    # then shifts or removes the 1 variable
    # runs docker compose etc
    # then injects everything after artisan or art where $@ variable is
    elif [ "$1" == "artisan" ] || [ "$1" == "art" ]; then
        shift 1
        docker-compose exec \
            app \
            php artisan "$@"

    elif [ "$1" == "composer" ] || [ "$1" == "comp" ]; then
        shift 1
        docker-compose exec \
            app \
            composer "$@"

    elif [ "$1" == "test" ]; then
        shift 1
        docker-compose exec \
            app \
            ./vendor/bin/phpunit "$@"

    # different command here runs 'run' instead of exec
    elif [ "$1" == "npm" ]; then
        shift 1
        docker-compose run --rm \
            node \
            npm "$@"

    elif [ "$1" == "yarn" ]; then
        shift 1
        docker-compose run --rm \
            node \
            yarn "$@"

    elif [ "$1" == "gulp" ]; then
        shift 1
        docker-compose run --rm \
            node \
            ./node_modules/.bin/gulp "$@"
    else
        docker-compose "$@"

    fi

else
    docker-compose ps
fi