version: '3.2'

services:
    app:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
        image: norrisdan/php:7.3
        networks:
            - net
        volumes:
            - .:/var/www/html
        ports:
            - ${APP_PORT}:80
        working_dir: /var/www/html
    cache:
        image: redis:alpine
        networks:
            - net
        volumes:
            - cachedata:/data

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT}:3306
        networks:
            - net
        volumes:
            - dbdata:/var/lib/mysql

    node:
        build:
            context: ./docker/node
            dockerfile: Dockerfile
        image: norrisdan/node:latest
        networks:
            - net
        volumes:
            - .:/opt
        working_dir: /opt
        command: echo hi

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - ${PMA_PORT}:80
        environment:
            - PMA_HOST=db
        networks:
            - net

networks:
    net:
        driver: bridge

volumes:
    dbdata:
        driver: local
    cachedata:
        driver: local
